#before_script:
#-  /home/gitlab-runner/anaconda3/bin/python ./setup.py install

stages:
  - build
  - test
  - cleanup
  
progressivis_build:
    stage: build
    script:
    - /bin/rm -rf build/;/home/gitlab-runner/anaconda3/bin/python ./setup.py install

progressivis_test:
    stage: test
    script:
    - /home/gitlab-runner/anaconda3/bin/python  ./setup.py nosetests
    
progressivis_cleanup:
    stage: cleanup
    script:
    - /bin/rm -rf /tmp/progressivis_*
    when: always
    
 #
 