language: python
python:
  - 2.7
  - 3.6

install: 
  - pip install -r requirements.txt
  - python -m pyroaring install --user
  - export LD_LIBRARY_PATH="`pwd`/croaring:$LD_LIBRARY_PATH"
  - python setup.py install

script: python setup.py nosetests
