package:
  name: progressivis
  version: 0.0.4

build:
  number: 1

source:
  git_rev: v0.0.4
  git_url: https://github.com/jdfekete/progressivis

requirements:
  build:
    - python
    - distribute
    - setuptools

  run:
    # progressivis
    - python
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - toposort
    - tdigest
    - pillow

    # server
    - flask
    - tornado >=4.0

test:
  imports:
    -

about:
  home: https://github.com/jdfekete/progressivis
  license: New BSD
  license_file: LICENCE
