package:
  name: progressivis
  version: 'nightly'

build:
  number: {{ environ.get('BINSTAR_BUILD', 1) }}

extra:
  channels:
    - progressivis

requirements:
  build:
    - python
    - distribute
    - setuptools

  run:
    # progressivis
    - python
    - requests
    - pyyaml
    - python-dateutil
    - jinja2
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - toposort
    - tdigest
    - pillow

    # server
    - flask
    - tornado >=4.0

    # bokeh
    - ipython
    - ipython-notebook
    - ipywidgets
    - matplotlib


test:
  requires:
    # docs
    - pygments
    - sphinx >=1.3.1
    - sphinx-bootstrap-theme
    - sphinxcontrib-httpdomain

  commands:
    - runserver -h        [linux64 or osx]

  imports:
    - progressivis

about:
  home: https://github.com/jdfekete/progressivis
  license: New BSD
